Revert "Merge branch '2.1.x' into BTTSKR_MINI_E3V3"
This reverts commit 4ce8358eb42764fd9c94f01d540cbb3086f1d9ab, reversing
changes made to a361e3cbca82504a13e33e7ae749e136a7b05a79.

diff --git a/buildroot/bin/opt_enable b/buildroot/bin/opt_enable
--- a/buildroot/bin/opt_enable
+++ b/buildroot/bin/opt_enable
@@ -1,21 +1,15 @@
-#!/usr/bin/env python
+#!/usr/bin/env bash
 
-import sys, os,config
+# exit on first failure
+set -e
 
-def main():
-    args = sys.argv[1:]
+SED=$(which gsed sed | head -n1)
 
-    for name in args:
-        changed = False
-
-        for file in config.FILES:
-            if os.path.exists(file):
-                if config.enable(file, name):
-                    changed = True
-
-        if not changed:
-            print(f"ERROR: Can't find {name}")
-            exit(1)
-
-if __name__ == "__main__":
-    main()
+for opt in "$@" ; do
+  DID=0 ; FOUND=0
+  for FN in Configuration Configuration_adv; do
+    "${SED}" -i "/^\(\s*\)\/\/\(\s*\)\(#define\s\+${opt}\b\)\( \?\)/{s//\1\2\3\4\4\4/;h};\${x;/./{x;q0};x;q9}" Marlin/$FN.h && DID=1
+    ((DID||FOUND)) || { grep -E "^\s*#define\s+${opt}\b" Marlin/$FN.h >/dev/null && FOUND=1 ; }
+  done
+  ((DID||FOUND)) || (echo "ERROR: $(basename $0) Can't find ${opt}" >&2 && exit 9)
+done
diff --git a/buildroot/bin/opt_set b/buildroot/bin/opt_set
--- a/buildroot/bin/opt_set
+++ b/buildroot/bin/opt_set
@@ -1,25 +1,17 @@
-#!/usr/bin/env python
+#!/usr/bin/env bash
 
-import sys, os, config
+# exit on first failure
+set -e
 
-def main():
-    args = sys.argv[1:]
-    if len(args) % 2 != 0:
-        print("ERROR: Please provide pairs of <name> <value>")
-        return
+SED=$(which gsed sed | head -n1)
 
-    for i in range(0, len(args), 2):
-        name = args[i]
-        value = args[i + 1]
-        changed = False
-
-        for file in config.FILES:
-            if os.path.exists(file):
-                if config.set(file, name, value):
-                    changed = True
-
-        if not changed:
-            config.add(config.FILES[0], name, value)
-
-if __name__ == "__main__":
-    main()
+while [[ $# > 1 ]]; do
+  DID=0
+  for FN in Configuration Configuration_adv; do
+    "${SED}" -i "/^\(\s*\)\/*\s*\(#define\s\+${1}\b\) *\(.*\)$/{s//\1\2 ${2} \/\/ \3/;h};\${x;/./{x;q0};x;q9}" Marlin/$FN.h && DID=1
+  done
+  ((DID)) ||
+    eval "echo '#define ${1} ${2}' >>Marlin/Configuration.h" ||
+      (echo "ERROR: opt_set Can't set or add ${1}" >&2 && exit 9)
+  shift 2
+done
